### ISSUE TITLE
Upload Meeting Notes

### ISSUE THREAD

**Issue by vsaw** [psycholold/TapToUnlock#1]
I will do this tomorrow (I guess)

@psycholold If you already have notes you could start with them and I add mine :)

**Comment by hbibel** [comment]
I can't start now, maybe tomorrow

**Comment by vsaw** [comment]
Meeting notes have been uploaded. Closing the issue now
https://github.com/psycholold/TapToUnlock/wiki/Meeting-Notes-2015-01-12
