### ISSUE TITLE
Update Project to use Android SDK Build Tools 21.1.2

### ISSUE THREAD

**Issue by vsaw** [psycholold/TapToUnlock#2]
Or is there a reason the project is still on 21.1.1?

Other than that the project import worked! Thanks for uploading it.

**Comment by hbibel** [comment]
There is no reason. We can change it.

**Comment by vsaw** [comment]
Alright then, please assign the issue to who of us should update the project

**Comment by hbibel** [comment]
The next person pushing on the develop branch should do it :wink:
